# Generated by Django 3.0.4 on 2020-07-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
