# Generated by Django 3.0.4 on 2020-07-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='digital',
        ),
    ]
